# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

use_frameworks! :linkage => :static

target 'LinechartNativeExample' do
  config = use_native_modules!
   
  pod 'React-Core', :path => '../node_modules/react-native/'
  
  pod 'DGCharts', '~> 5.1.0'
 
  
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # target 'LinechartNativeExampleTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Modül tanımlamaları ve Swift ayarları için
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['DEFINES_MODULE'] = 'YES'
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['SWIFT_INSTALL_OBJC_HEADER'] = 'YES'
       # config.build_settings['SWIFT_OBJC_INTERFACE_HEADER_NAME'] = 'ReactNativeLineChartNative-Swift.h'
      end
    end
  end
end
